<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\NewFolder\**" />
    <Content Remove="wwwroot\NewFolder\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder\**" />
    <None Remove="wwwroot\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\NewFolder1\" />
    <Folder Include="Views\NewFolder2\" />
    <Folder Include="Views\Work\" />
    <Folder Include="Views\NewFolder\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.27">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
